/*
 * Code generator: turns the editor's draft back into a ready-to-commit
 * src/data/chapters.ts. The site has no backend by design, so "save" is
 * export → replace the file → push; the repo stays the single source of
 * truth and the deploy pipeline stays a plain static build.
 */
import type { EditableChapter, SiteContent } from "./types";

const s = (value: string) => JSON.stringify(value);

type PinShape = {
  city: string;
  country: string;
  lat: number;
  lng: number;
  photos?: { src: string; caption?: string }[];
  panel?: { x: number; y: number; w?: number };
};

function photoList(photos: PinShape["photos"]): string {
  const kept = (photos ?? []).filter((photo) => photo.src.trim());
  if (!kept.length) return "";
  const items = kept
    .slice(0, 2)
    .map((photo) =>
      photo.caption?.trim()
        ? `{ src: ${s(photo.src.trim())}, caption: ${s(photo.caption.trim())} }`
        : `{ src: ${s(photo.src.trim())} }`,
    );
  return `, photos: [${items.join(", ")}]`;
}

function pinLine(pin: PinShape) {
  const photos = photoList(pin.photos);
  // A panel position is only meaningful alongside photos — dropping it
  // otherwise keeps the exported file free of dead fields.
  const panel =
    photos && pin.panel
      ? `, panel: { x: ${pin.panel.x}, y: ${pin.panel.y}${
          pin.panel.w !== undefined ? `, w: ${pin.panel.w}` : ""
        } }`
      : "";
  return `{ city: ${s(pin.city)}, country: ${s(pin.country)}, lat: ${pin.lat}, lng: ${pin.lng}${photos}${panel} }`;
}

function chapterBlock(chapter: EditableChapter): string {
  const lines: string[] = ["  {"];
  lines.push(`    id: ${s(chapter.id)},`);
  lines.push(`    title: ${s(chapter.title)},`);
  lines.push(`    org: ${s(chapter.org)},`);
  lines.push(`    role: ${s(chapter.role)},`);
  lines.push(`    dates: ${s(chapter.dates)},`);
  lines.push(`    blurb:\n      ${s(chapter.blurb)},`);
  if (chapter.pins.length === 1) {
    lines.push(`    pins: [${pinLine(chapter.pins[0])}],`);
  } else {
    lines.push(`    pins: [`);
    for (const pin of chapter.pins) lines.push(`      ${pinLine(pin)},`);
    lines.push(`    ],`);
  }
  if (chapter.arcs && chapter.arcs.length) {
    lines.push(`    arcs: [`);
    for (const [from, to] of chapter.arcs) lines.push(`      [${from}, ${to}],`);
    lines.push(`    ],`);
  }
  lines.push(`    altitude: ${chapter.altitude},`);
  if (chapter.link) lines.push(`    link: ${s(chapter.link)},`);
  lines.push("  },");
  return lines.join("\n");
}

export function generateChaptersTs(
  chapters: EditableChapter[],
  site: SiteContent,
): string {
  return `/*
 * All portfolio content lives in this file — the six chapters, their pins,
 * and every line of page copy. Components render from here and hard-code
 * nothing. Generated by the private editor (/edit.html); hand edits are
 * equally fine.
 */

/** One recon-photo slot for a location's callout panel. */
export interface PhotoSlot {
  /** Image URL — drop a file in public/photos and reference it as
   *  "/photos/name.jpg", or use any absolute https URL. */
  src: string;
  caption?: string;
}

export interface Pin {
  city: string;
  country: string;
  lat: number;
  lng: number;
  /** Sat-photo callouts for this location — up to two. Fill these in
   *  later (hand-edit or the private editor at /edit.html); empty or
   *  missing means no panel renders. */
  photos?: PhotoSlot[];
  /** Exact screen placement for this pin's photo panel: its top-left
   *  corner as percentages of the viewport (0–100, x across / y down),
   *  and optionally its width as a percentage of the screen's width
   *  (\`w\`; omit for the responsive default). Set on the editor's
   *  placement page; omit entirely for the default stack. */
  panel?: { x: number; y: number; w?: number };
}

export interface Chapter {
  id: string;
  title: string;
  org: string;
  role: string;
  dates: string;
  blurb: string;
  /** Where it happened. Never empty — the camera, eyebrow, and dive all
   *  read pins[0], so the type demands at least one. */
  pins: [Pin, ...Pin[]];
  /** Pairs of indexes into \`pins\`, drawn as animated arcs while the chapter is active. */
  arcs?: [number, number][];
  /** Globe camera altitude when this chapter is active. */
  altitude: number;
  link?: string;
}

export const chapters: Chapter[] = [
${chapters.map(chapterBlock).join("\n")}
];

export const site = {
  name: ${s(site.name)},
  kicker: ${s(site.kicker)},
  identity:
    ${s(site.identity)},
  scrollCue: ${s(site.scrollCue)},
  about:
    ${s(site.about)},
  chaptersHeading: ${s(site.chaptersHeading)},
  resumeHeading: ${s(site.resumeHeading)},
  contactHeading: ${s(site.contactHeading)},
  contact: [
${site.contact.map((c) => `    { label: ${s(c.label)}, href: ${s(c.href)} },`).join("\n")}
  ],
  earthDown: ${s(site.earthDown)},
  earthUp: ${s(site.earthUp)},
  cycleLabel: ${s(site.cycleLabel)},
  loadingLabel: ${s(site.loadingLabel)},
  poleEgg: ${s(site.poleEgg)},
  ibidLabel: ${s(site.ibidLabel)},
  expandLabel: ${s(site.expandLabel)},
  closeLabel: ${s(site.closeLabel)},
  footerNote:
    ${s(site.footerNote)},
  skipLinkLabel: ${s(site.skipLinkLabel)},
};
`;
}
