/*
 * Code generator: turns the editor's draft back into a ready-to-commit
 * src/data/chapters.ts. The site has no backend by design, so "save" is
 * export → replace the file → push; the repo stays the single source of
 * truth and the deploy pipeline stays a plain static build.
 */
import type { EditableChapter, SiteContent } from "./types";

const s = (value: string) => JSON.stringify(value);

function pinLine(pin: { city: string; country: string; lat: number; lng: number }) {
  return `{ city: ${s(pin.city)}, country: ${s(pin.country)}, lat: ${pin.lat}, lng: ${pin.lng} }`;
}

function chapterBlock(chapter: EditableChapter): string {
  const lines: string[] = ["  {"];
  lines.push(`    id: ${s(chapter.id)},`);
  lines.push(`    title: ${s(chapter.title)},`);
  lines.push(`    org: ${s(chapter.org)},`);
  lines.push(`    role: ${s(chapter.role)},`);
  lines.push(`    dates: ${s(chapter.dates)},`);
  lines.push(`    blurb:\n      ${s(chapter.blurb)},`);
  if (chapter.pins.length === 1) {
    lines.push(`    pins: [${pinLine(chapter.pins[0])}],`);
  } else {
    lines.push(`    pins: [`);
    for (const pin of chapter.pins) lines.push(`      ${pinLine(pin)},`);
    lines.push(`    ],`);
  }
  if (chapter.arcs && chapter.arcs.length) {
    lines.push(`    arcs: [`);
    for (const [from, to] of chapter.arcs) lines.push(`      [${from}, ${to}],`);
    lines.push(`    ],`);
  }
  lines.push(`    altitude: ${chapter.altitude},`);
  if (chapter.link) lines.push(`    link: ${s(chapter.link)},`);
  lines.push("  },");
  return lines.join("\n");
}

export function generateChaptersTs(
  chapters: EditableChapter[],
  site: SiteContent,
): string {
  return `/*
 * All portfolio content lives in this file — the six chapters, their pins,
 * and every line of page copy. Components render from here and hard-code
 * nothing. Generated by the private editor (/edit.html); hand edits are
 * equally fine.
 */

export interface Pin {
  city: string;
  country: string;
  lat: number;
  lng: number;
}

export interface Chapter {
  id: string;
  title: string;
  org: string;
  role: string;
  dates: string;
  blurb: string;
  /** Where it happened. Never empty — the camera, eyebrow, and dive all
   *  read pins[0], so the type demands at least one. */
  pins: [Pin, ...Pin[]];
  /** Pairs of indexes into \`pins\`, drawn as animated arcs while the chapter is active. */
  arcs?: [number, number][];
  /** Globe camera altitude when this chapter is active. */
  altitude: number;
  link?: string;
}

export const chapters: Chapter[] = [
${chapters.map(chapterBlock).join("\n")}
];

export const site = {
  name: ${s(site.name)},
  kicker: ${s(site.kicker)},
  identity:
    ${s(site.identity)},
  scrollCue: ${s(site.scrollCue)},
  about:
    ${s(site.about)},
  chaptersHeading: ${s(site.chaptersHeading)},
  contactHeading: ${s(site.contactHeading)},
  contact: [
${site.contact.map((c) => `    { label: ${s(c.label)}, href: ${s(c.href)} },`).join("\n")}
  ],
  earthDown: ${s(site.earthDown)},
  earthUp: ${s(site.earthUp)},
  footerNote:
    ${s(site.footerNote)},
  skipLinkLabel: ${s(site.skipLinkLabel)},
};
`;
}
