/*
 * All portfolio content lives in this file — the six chapters, their pins,
 * and every line of page copy. Components render from here and hard-code
 * nothing. Generated by the private editor (/edit.html); hand edits are
 * equally fine.
 */

/** One recon-photo slot for a location's callout panel. */
export interface PhotoSlot {
  /** Image URL — drop a file in public/photos and reference it as
   *  "/photos/name.jpg", or use any absolute https URL. */
  src: string;
  caption?: string;
}

export interface Pin {
  city: string;
  country: string;
  lat: number;
  lng: number;
  /** Sat-photo callouts for this location — up to two. Fill these in
   *  later (hand-edit or the private editor at /edit.html); empty or
   *  missing means no panel renders. */
  photos?: PhotoSlot[];
  /** Exact screen placement for this pin's photo panel: its top-left
   *  corner as percentages of the viewport (0–100, x across / y down).
   *  Set on the editor's placement page; omit for the default stack. */
  panel?: { x: number; y: number };
}

export interface Chapter {
  id: string;
  title: string;
  org: string;
  role: string;
  dates: string;
  blurb: string;
  /** Where it happened. Never empty — the camera, eyebrow, and dive all
   *  read pins[0], so the type demands at least one. */
  pins: [Pin, ...Pin[]];
  /** Pairs of indexes into `pins`, drawn as animated arcs while the chapter is active. */
  arcs?: [number, number][];
  /** Globe camera altitude when this chapter is active. */
  altitude: number;
  link?: string;
}

export const chapters: Chapter[] = [
  {
    id: "shein",
    title: "Agentic Marketing Systems",
    org: "SHEIN",
    role: "Global Marketing Intern",
    dates: "Jun – Aug 2026",
    blurb:
      "Built agentic AI workflows in Dify and Apify that automate competitive brand research and influencer evaluation across SHEIN's portfolio of 10+ sub-brands, cutting multi-day manual research to minutes per brand. Shipped bilingual report generation with live web-search grounding and anti-fabrication guardrails, plus an end-to-end Instagram intelligence pipeline that turns captions and engagement metrics into structured spreadsheets.",
    pins: [{ city: "Caohejing · Shanghai", country: "China", lat: 31.1727, lng: 121.3947, photos: [{ src: "/photos/2026-07-06-10.25.21.webp" }, { src: "/photos/2026-07-06-10.26.23.webp" }], panel: { x: 4.5, y: 11.5 } }],
    altitude: 0.035,
  },
  {
    id: "chenman",
    title: "Fashion Photography",
    org: "Chen Man Studio",
    role: "Camera Assistant",
    dates: "May – Jun 2025",
    blurb:
      "Assisted photographer Chen Man on roughly 20 commercial fashion shoots — lighting setups, on-set production logistics, and shoot scheduling.",
    pins: [{ city: "West Bund · Shanghai", country: "China", lat: 31.169, lng: 121.456, photos: [{ src: "/photos/5c83c842-4cd1-4a60-985c-ff8167a071cf-1-105-c.jpeg" }, { src: "/photos/5251b04b-1af6-4a44-be9e-dfa0b3c63ae1-1-105-c.jpeg" }], panel: { x: 43.3, y: 2.3 } }],
    altitude: 0.022,
    link: "https://www.yukalbert.com/photograph",
  },
  {
    id: "film-production",
    title: "Film Production",
    org: "",
    role: "Production Crew",
    dates: "",
    blurb:
      "On-set production work across feature and commercial sets.",
    pins: [
      { city: "Beijing", country: "China", lat: 39.9042, lng: 116.4074, photos: [{ src: "/photos/a572327e-cbad-462b-b655-e4841e658365-1-105-c.jpeg" }], panel: { x: 3.2, y: 10.8 } },
      { city: "Shenzhen", country: "China", lat: 22.5431, lng: 114.0579, photos: [{ src: "/photos/d536d1e0-a80e-41b8-bd1c-74cdbb7687dc-1-105-c.jpeg" }], panel: { x: 41.1, y: 24.4 } },
    ],
    arcs: [
      [0, 1],
    ],
    altitude: 0.8,
    link: "https://www.yukalbert.com/filmset",
  },
  {
    id: "old-road",
    title: "Old Road; New Chapter",
    org: "Photojournalism project with Liu Heung Shing, Pulitzer Prize–winning photojournalist",
    role: "Production Assistant",
    dates: "Jun 2024 – Jul 2025",
    blurb:
      "Production assistance across Central Asia and the Middle East, documenting cultural and geopolitical change — the journey behind the Central Asia, Israel, and Iran photo series.",
    pins: [
      { city: "Almaty", country: "Kazakhstan", lat: 43.238, lng: 76.8829, photos: [{ src: "/photos/0c0ea97a-0203-49b3-b9c0-94fec94a3cb3-1-105-c.jpeg" }], panel: { x: 39.6, y: 12.6 } },
      { city: "Samarkand", country: "Uzbekistan", lat: 39.6542, lng: 66.9597, photos: [{ src: "/photos/9501c106-4612-4ce6-a274-d390ddfdcc3e-1-105-c.jpeg" }], panel: { x: 0, y: 18.7 } },
      { city: "Tehran", country: "Iran", lat: 35.6892, lng: 51.389, photos: [{ src: "/photos/66bd7afc-4e51-4d82-857e-06965a0c3f8f-1-105-c.jpeg" }, { src: "/photos/3a5e2319-a5b8-4bef-a38d-ea2d2be7bcb0-1-105-c.jpeg" }], panel: { x: 39.8, y: 8.7 } },
      { city: "Jerusalem", country: "Israel", lat: 31.7683, lng: 35.2137, photos: [{ src: "/photos/bb0f4995-a011-4c57-baa6-e2a6a6c06f9c-1-105-c.jpeg" }, { src: "/photos/7a7d93f4-b95b-4530-895c-3e5d63c223bf-1-105-c.webp" }], panel: { x: 40.1, y: 10 } },
    ],
    arcs: [
      [0, 1],
      [1, 2],
      [2, 3],
    ],
    altitude: 0.85,
    link: "https://www.yukalbert.com/central-asia",
  },
  {
    id: "maga-doc",
    title: "MAGA Hat Production in China",
    org: "Independent documentary",
    role: "Director & Cinematographer",
    dates: "Jul 2024",
    blurb:
      "Solo-directed, shot, and edited a documentary following MAGA hats from the factories of Yiwu through the Port of Shanghai to a rally crowd in Pennsylvania. All-American High School Film Festival Spark Award — top 1% of 2,700+ submissions.",
    pins: [
      { city: "Yiwu", country: "China", lat: 29.3069, lng: 120.0753, photos: [{ src: "/photos/2026-07-06-10.47.02.webp" }], panel: { x: 1.1, y: 16 } },
      { city: "Port of Shanghai", country: "China", lat: 30.6289, lng: 122.0639, photos: [{ src: "/photos/470f90c4-25c2-46df-bfb0-faa8b35a7f9c-1-102-o.webp" }], panel: { x: 41.4, y: 33.4 } },
      { city: "Butler, PA", country: "United States", lat: 40.8612, lng: -79.8953, photos: [{ src: "/photos/2026-07-06-10.46.26.webp" }], panel: { x: 3, y: 13.5 } },
    ],
    arcs: [
      [0, 1],
      [1, 2],
    ],
    altitude: 0.85,
  },
  {
    id: "dacameraroll",
    title: "@dacameraroll",
    org: "Deerfield Academy",
    role: "President, Deerfield Academy Cameraroll",
    dates: "Sep 2022 – May 2026",
    blurb:
      "Led a team of 10+ photographers covering ~200 campus events, reaching 100,000+ monthly views. Photographed 100+ senior portrait sessions featured in the yearbook.",
    pins: [{ city: "Deerfield, MA", country: "United States", lat: 42.5459, lng: -72.6037, photos: [{ src: "/photos/img-5495.webp" }], panel: { x: 41.6, y: 12.9 } }],
    altitude: 0.65,
    link: "https://www.yukalbert.com/school",
  },
];

export const site = {
  name: "Albert Yuk",
  kicker: "Production log · 2022 – 2026",
  identity:
    "Filmmaker, photographer, and marketing technologist. Six chapters of work, plotted where they happened.",
  scrollCue: "Scroll — the globe follows",
  about:
    "Deerfield Academy, Class of 2026. The work below spans a commercial photo studio, feature and commercial film sets, a photojournalism journey with Liu Heung Shing, a festival-winning documentary, and agentic marketing systems at SHEIN — ordered as chapters, each pinned to the place it happened.",
  chaptersHeading: "Chapters",
  contactHeading: "Contact",
  contact: [
    { label: "yukalbert.com", href: "https://www.yukalbert.com" },
    { label: "yzy.albert@gmail.com", href: "mailto:yzy.albert@gmail.com" },
    { label: "Photographs", href: "https://www.yukalbert.com/photograph" },
    { label: "Film sets", href: "https://www.yukalbert.com/filmset" },
    { label: "Central Asia series", href: "https://www.yukalbert.com/central-asia" },
    { label: "@dacameraroll", href: "https://www.yukalbert.com/school" },
  ],
  earthDown: "Down to earth",
  earthUp: "Back to orbit",
  cycleLabel: "Next location",
  loadingLabel: "Plotting the atlas",
  poleEgg: "to be continued?",
  ibidLabel: "Ibid.",
  footerNote:
    "Single static page. The globe is drawn locally from vector data (Natural Earth; river detail © OpenStreetMap contributors); nothing on this site tracks you.",
  skipLinkLabel: "Skip to chapters",
};
